// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4r9BfAZd4-F8qlFTSozz1_sZCtZZpyN0',
    appId: '1:861357360609:web:ef49341a77503e89de7ea0',
    messagingSenderId: '861357360609',
    projectId: 'todoapp-b9bd1',
    authDomain: 'todoapp-b9bd1.firebaseapp.com',
    storageBucket: 'todoapp-b9bd1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo2hSKNuSNx5aEnB1gK3PqhJWdLJv6aLM',
    appId: '1:861357360609:android:9891288962cfbdd8de7ea0',
    messagingSenderId: '861357360609',
    projectId: 'todoapp-b9bd1',
    storageBucket: 'todoapp-b9bd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8SfnEuC9bKUQtOxgWvUAQh4MCEIVY-6Y',
    appId: '1:861357360609:ios:e517f201da2d8cfade7ea0',
    messagingSenderId: '861357360609',
    projectId: 'todoapp-b9bd1',
    storageBucket: 'todoapp-b9bd1.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8SfnEuC9bKUQtOxgWvUAQh4MCEIVY-6Y',
    appId: '1:861357360609:ios:fa4bfce1abe2e03fde7ea0',
    messagingSenderId: '861357360609',
    projectId: 'todoapp-b9bd1',
    storageBucket: 'todoapp-b9bd1.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
